[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.63"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
web-sys = "0.3.63"
yew = { version = "0.20.0", features = ["csr"] }
yew-hooks = "0.2.0"
maspace = { path = ".." }
