name: Deploy

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v3
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: >-
          cd ./demo &&
          trunk build --release --public-url maspace &&
          cp -r ./dist/ ../public/ &&
          cd ..
      - run: cp -r ./demo/dist/ ./public/
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
